"""empty message

Revision ID: 339cdbe0888d
Revises: 
Create Date: 2020-07-14 20:12:29.567876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339cdbe0888d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookfile')
    # ### end Alembic commands ###
