"""empty message

Revision ID: 952f4d7fda4d
Revises: e082764af0b2
Create Date: 2020-07-11 02:45:45.680787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952f4d7fda4d'
down_revision = 'e082764af0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image')
    # ### end Alembic commands ###
