"""empty message

Revision ID: a8d82b425513
Revises: 6c1e7742d742
Create Date: 2020-07-12 15:34:24.883758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d82b425513'
down_revision = '6c1e7742d742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('comment', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'comment')
    # ### end Alembic commands ###
